version: '3.8'

services:
  # Flask Application
  web:
    build: .
    container_name: flask_multi_store
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
